// Code generated by mockery v1.0.0. DO NOT EDIT.

package ethsignermocks

import (
	ethsigner "github.com/hyperledger/firefly-signer/pkg/ethsigner"
	ethtypes "github.com/hyperledger/firefly-signer/pkg/ethtypes"

	mock "github.com/stretchr/testify/mock"
)

// Wallet is an autogenerated mock type for the Wallet type
type Wallet struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Wallet) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccounts provides a mock function with given fields:
func (_m *Wallet) GetAccounts() []ethtypes.Address {
	ret := _m.Called()

	var r0 []ethtypes.Address
	if rf, ok := ret.Get(0).(func() []ethtypes.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ethtypes.Address)
		}
	}

	return r0
}

// Initialize provides a mock function with given fields:
func (_m *Wallet) Initialize() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Refresh provides a mock function with given fields:
func (_m *Wallet) Refresh() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sign provides a mock function with given fields: addr, tx, chainID
func (_m *Wallet) Sign(addr ethtypes.Address, tx *ethsigner.Transaction, chainID int64) ([]byte, error) {
	ret := _m.Called(addr, tx, chainID)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(ethtypes.Address, *ethsigner.Transaction, int64) []byte); ok {
		r0 = rf(addr, tx, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(ethtypes.Address, *ethsigner.Transaction, int64) error); ok {
		r1 = rf(addr, tx, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
